# Generated by Django 4.1.1 on 2022-10-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_options_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('EL', 'Electronic'), ('CA', 'Car'), ('FO', 'Food'), ('SP', 'Sport'), ('SA', 'Smartphones'), ('CL', 'Clothes')], default='not_defined', max_length=15),
        ),
    ]
